"use server";

import { prisma } from "@/lib/prisma";
import { log } from "@/utils/logger";

type Agent = { name: string };

export async function summarizeSelection(selection: string[], agent: Agent) {
  return {
    title: `Summary of ${selection.length} items`,
    text: `This summary was generated by ${agent.name} for selected nodes.`,
  };
}

type CreateNodeInput = {
  title: string;
  content: string;
  tags: string[];
};

export async function createNode(data: CreateNodeInput) {
  const node = await prisma.node.create({
    data: {
      label: data.title,
      note: data.content,
      x: Math.random() * 400,
      y: Math.random() * 300,
    },
  });
  log.info("[GraphActions] Created node", node.id);
  return node;
}

export async function linkNodes(sourceId: string, targetId: string) {
  await prisma.edge.create({
    data: { sourceId, targetId },
  });
  log.info("[GraphActions] Linked", sourceId, "->", targetId);
}

